server:
  port: 7070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vs_learning?useSSL=false
    username: root
    password: Sem@2024
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/repository/*.xml
  type-aliases-package: com.example.IdCard.model.entity

security:
  secret-key: lpa8LvsweKxWPozSuczHSSDtPzJDh9BtBxdYWjaerfeVE1pOyicicSzJ4XGL72Iw
  expration: 300000  #1000*60*5


